import Head from 'next/head';
import Image from 'next/image';
import { useState, useEffect, useRef } from 'react';
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router';
import  dayjs  from 'dayjs';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
import { useTheme, ThemeProvider, createTheme } from '@mui/material/styles';
import TextField from '@mui/material/Input';
// import { getDatabase, onValue, ref } from 'firebase/database';
// import { getAnalytics, logEvent } from "firebase/analytics";
// import { collection, addDoc } from 'firebase/firestore';
//import { initializeApp } from 'firebase/app';
//import configuration from '../configuration';

//import TagManager from 'react-gtm-module'

//import { initializeApp } from "firebase/app";
//const app2 = initializeApp(configuration);



export default function Home(props) {  
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Hockey Count</title>
        <meta name="description" content="Generated by Sebastien Deraspe" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        Bonjour!!! 
 
      </main>
    </div>
  )
}

