import Head from 'next/head';
import styles from '../styles/Home.module.css'
import { TextField } from '@mui/material';;
import { useState, useEffect, useRef } from 'react';
import { useRouter } from 'next/router';

// Import the functions you need from the SDKs you need
//import { initializeApp } from "firebase/app";
//import { getAnalytics } from "firebase/analytics";



function Signup() {

  const router = useRouter();
  const [firstName, SetFirstName] = useState();
  const [lastName, SetLastName] = useState();
  const [password, SetPassword] = useState();
  const [email, SetEmail] = useState();
  
  const initialState = [];
  const validations = [];
  
  // const { values, isValid, errors, changeHandler, submitHanler  } = Useform(
  //   initialState,
  //   validations
  // );
  
  async function fetchUser() {

    const requestOptions = {
      methode : "PUT",
      headers : {      
        "content-type" : "application/json"
      }, 
      body: JSON.stringify({
        firstName: firstName,
        lastName: lastName,
        password: password,
        email: email            
      })
  };

    try {
      const response = await fetch('http://localhost:3000/api/user/', requestOptions);
      console.log(response.status);
    } catch (error) {
      //console.log(response.status, response.statusText);
      console.log(error);    
    }  
  }

  return (
    <div >
    <Head>
      <title>Hockey Count Sign Up</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.form} >
      <h1>Sign Up</h1>
      <div className="section">
        <TextField
//        onChange={SetFirstName}
        required
        id="firstName"
        label="First Name"
        name="firstName"
        value={firstName}
        variant="outlined"    
        />
      </div>

      <div className="section">
        <TextField
    //    onChange={SetLastName}
        required
        id="lasttName"
        label="Last Name"
        name="lastName"
        value={lastName}
        variant="outlined"    
        />
      </div>

      <div className="section">
        <TextField
    //    onChange={SetPassword}
        required
        id="password"
        label="Password"
        name="password"
        value={password}
        variant="outlined"    
        />
      </div>

      <div className="section">
        <TextField
   //     onChange={SetEmail}
        required
        id="email"
        label="Email"
        name="email"
        value={email}
        variant="outlined"    
        />
      </div>
      <button className="ui primary button login" onClick={fetchUser} type="submit">
              Sign Up
            </button>

    </main>
    </div>
  );
}

export default Signup;
